version: "3.9"

services:
  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128Mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: whatsappbot
    ports:
      - "5432:5432"
    networks:
      - bot-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8006:8080"
    networks:
      - bot-network
    # Uncomment the next line in production
    # depends_on:
    #   - postgres

  redis:
    image: redis/redis-stack
    container_name: redis-stack
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - bot-network
    environment:
      REDIS_PASSWORD: secretpassword
    command: [ "redis-server", "--requirepass", "secretpassword" ]


  # chatbotapp:
  #   build: .
  #   container_name: chatbot-app
  #   ports:
  #     - "3001:3001"
  #   volumes:
  #     - .:/app
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   user: "chrome"
  #   group_add:
  #     - "999"  # This is your host's docker group ID
  #   networks:
  #     - bot-network
  #   restart: always
  #   depends_on:
  #     - postgres
  #     - redis

networks:
  bot-network:
    name: bot-network
